#!/usr/bin/env sh
# ============================================================================
# Botapolis · post-commit (standalone, non-husky)
# ----------------------------------------------------------------------------
# This is a 1:1 mirror of .husky/post-commit, kept in /scripts/git-hooks/
# so it can be installed in environments where husky isn't configured
# (e.g. a bare clone on the Mac Mini that pulls but never commits, or a
# personal dev clone that prefers vanilla git hooks).
#
# Install:
#   ln -s "$(pwd)/scripts/git-hooks/post-commit.sh" .git/hooks/post-commit
#   chmod +x .git/hooks/post-commit
#
# DO NOT edit this file independently of .husky/post-commit — they must
# match. Source of truth is .husky/post-commit; copy changes here on bump.
# ============================================================================
set -e

branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" != "main" ]; then
  exit 0
fi

sha=$(git rev-parse HEAD)
changed=$(git diff-tree --no-commit-id --name-only --diff-filter=AM -r "$sha" \
  | grep -E '^content/(comparisons|alternatives|guides|best|news|pricing)/(en|ru)/.*\.mdx$' \
  || true)

if [ -z "$changed" ]; then
  exit 0
fi

load_env() {
  if [ -f .env.local ]; then
    grep -E "^$1=" .env.local | head -n1 | sed -E "s/^$1=//" | sed -E 's/^"//; s/"$//'
  fi
}

SECRET=$(load_env REVALIDATE_SECRET)
SITE_URL=$(load_env NEXT_PUBLIC_SITE_URL)
SITE_URL="${SITE_URL:-https://botapolis.com}"

if [ -z "$SECRET" ]; then
  echo "[post-commit] REVALIDATE_SECRET not set in .env.local — skipping webhook"
  exit 0
fi

mdx_primary_keyword() {
  awk '
    BEGIN { inFm=0 }
    /^---[[:space:]]*$/ { inFm = !inFm; next }
    inFm && /^primaryKeyword:/ {
      sub(/^primaryKeyword:[[:space:]]*/, "")
      gsub(/^"|"$/, "")
      print
      exit
    }
  ' "$1"
}

slug_from_path() {
  echo "$1" | sed -E 's|^content/[^/]+/(en\|ru)/(.+)\.mdx$|\2|'
}

files_json=""
while IFS= read -r f; do
  [ -z "$f" ] && continue
  kw=$(mdx_primary_keyword "$f" 2>/dev/null | sed 's/"/\\"/g')
  slug=$(slug_from_path "$f")
  # Comparison files only: inline the MDX body as base64 so the webhook can
  # bridge into public.comparisons without an outbound raw.githubusercontent
  # fetch (Vercel CPU saver — added 2026-05-30). Other content types don't
  # use the body server-side, so we don't pay the payload size.
  content_b64=""
  case "$f" in
    content/comparisons/*) content_b64=$(base64 < "$f" | tr -d '\n') ;;
  esac
  entry="{\"path\":\"$f\",\"primary_keyword\":\"$kw\",\"slug\":\"$slug\",\"content_b64\":\"$content_b64\"}"
  if [ -z "$files_json" ]; then files_json="$entry"
  else files_json="$files_json,$entry"
  fi
done <<EOF
$changed
EOF

payload="{\"files\":[$files_json],\"commit_sha\":\"$sha\"}"

echo "[post-commit] notifying $SITE_URL/api/agents/article-published"
http_code=$(curl -s -o /tmp/botapolis-post-commit.log -w "%{http_code}" \
  --max-time 20 \
  -X POST "$SITE_URL/api/agents/article-published?secret=$SECRET" \
  -H "Content-Type: application/json" \
  -d "$payload" || echo "000")

if [ "$http_code" = "200" ]; then
  echo "[post-commit] webhook OK"
else
  echo "[post-commit] webhook returned $http_code — see /tmp/botapolis-post-commit.log"
fi

exit 0
